# Generated by Django 5.2.5 on 2025-11-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_customer_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
