# Generated by Django 5.2.5 on 2025-11-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_order_address_special_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
