# Generated by Django 5.2.5 on 2025-11-14 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_remove_employee_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
    ]
