# Generated by Django 5.2.5 on 2025-09-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menuitem_description_remove_menuitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='order',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
